"""empty message

Revision ID: 149da80c5b65
Revises: 710037cf9869
Create Date: 2025-03-09 23:03:32.924361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149da80c5b65'
down_revision = '710037cf9869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.create_index('idx_manager_name', ['name'], unique=False)
        batch_op.create_index('idx_manager_username', ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.drop_index('idx_manager_username')
        batch_op.drop_index('idx_manager_name')

    # ### end Alembic commands ###
