"""empty message

Revision ID: 2414e5a01389
Revises: 7176636d1e62
Create Date: 2025-03-07 00:18:44.275381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2414e5a01389'
down_revision = '7176636d1e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.create_index('idx_manager_name', ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.drop_index('idx_manager_name')

    # ### end Alembic commands ###
