"""Initial migration with Application models

Revision ID: 24683738db3f
Revises: 
Create Date: 2025-03-02 14:54:12.217935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24683738db3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index('idx_branch_name', ['name'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('request_datetime', sa.DateTime(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('in-progress', 'closed', 'transferred', name='application_status'), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('idx_phone_number', ['phone_number'], unique=False)

    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('updated_fields', sa.JSON(), nullable=False),
    sa.Column('previous_values', sa.JSON(), nullable=False),
    sa.Column('new_values', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('old_branch_id', sa.Integer(), nullable=False),
    sa.Column('new_branch_id', sa.Integer(), nullable=False),
    sa.Column('transferred_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['new_branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['old_branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_transfers')
    op.drop_table('application_history')
    op.drop_table('managers')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('idx_phone_number')

    op.drop_table('applications')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index('idx_branch_name')

    op.drop_table('branches')
    # ### end Alembic commands ###
