"""empty message

Revision ID: 350c62da9589
Revises: d7533d64392b
Create Date: 2025-02-21 23:40:02.457283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350c62da9589'
down_revision = 'd7533d64392b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
