"""Add deleted_at to Application

Revision ID: 366c3a43e1b3
Revises: 24683738db3f
Create Date: 2025-03-03 20:09:12.904629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '366c3a43e1b3'
down_revision = '24683738db3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('request_datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
