"""empty message

Revision ID: 7176636d1e62
Revises: fcfab1d9eb93
Create Date: 2025-03-06 20:51:59.890250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7176636d1e62'
down_revision = 'fcfab1d9eb93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('application_transfers')
    with op.batch_alter_table('application_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=255), nullable=True))
        batch_op.drop_column('changed_at')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('deleted_by', sa.String(length=255), nullable=True))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('in-progress', 'closed', 'transferred', name='application_status'),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.drop_constraint('applications_branch_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'branches', ['branch_name'], ['name'])
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('managers_branch_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'branches', ['branch_name'], ['name'])
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('managers_branch_id_fkey', 'branches', ['branch_id'], ['id'])
        batch_op.drop_column('role')
        batch_op.drop_column('branch_name')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('applications_branch_id_fkey', 'branches', ['branch_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('in-progress', 'closed', 'transferred', name='application_status'),
               nullable=True)
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('branch_name')

    with op.batch_alter_table('application_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('updated_by')
        batch_op.drop_column('updated_at')

    op.create_table('application_transfers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_branch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_branch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transferred_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name='application_transfers_application_id_fkey'),
    sa.ForeignKeyConstraint(['new_branch_id'], ['branches.id'], name='application_transfers_new_branch_id_fkey'),
    sa.ForeignKeyConstraint(['old_branch_id'], ['branches.id'], name='application_transfers_old_branch_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='application_transfers_pkey')
    )
    op.drop_table('admin')
    # ### end Alembic commands ###
