"""empty message

Revision ID: 776a5aefef93
Revises: 
Create Date: 2025-02-20 22:44:05.191862

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '776a5aefef93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('managers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('branch_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('requests',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('client_name', sa.String(length=255), nullable=False),
                    sa.Column('phone_number', sa.String(length=20), nullable=False),
                    sa.Column('request_datetime', sa.DateTime(), nullable=False),
                    sa.Column('branch_id', sa.Integer(), nullable=False),
                    sa.Column('product', sa.String(length=255), nullable=False),
                    sa.Column('status', sa.Enum('В обработке', 'Закрыта', 'Перенаправлена', name='request_status'),
                              nullable=True),
                    sa.Column('notes', sa.Text(), nullable=True),
                    sa.Column('history', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('request_transfers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('request_id', sa.Integer(), nullable=False),
                    sa.Column('old_branch_id', sa.Integer(), nullable=False),
                    sa.Column('new_branch_id', sa.Integer(), nullable=False),
                    sa.Column('transferred_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['new_branch_id'], ['branches.id'], ),
                    sa.ForeignKeyConstraint(['old_branch_id'], ['branches.id'], ),
                    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_transfers')
    op.drop_table('requests')
    op.drop_table('managers')
    op.drop_table('branches')
    # ### end Alembic commands ###
