"""empty message

Revision ID: 7a322c79ff14
Revises: f93cc87bc4e1
Create Date: 2025-03-03 22:23:51.019891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a322c79ff14'
down_revision = 'f93cc87bc4e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('idx_is_deleted', ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('idx_is_deleted')

    # ### end Alembic commands ###
