"""Upgrading production database

Revision ID: 9e546e920376
Revises: 350c62da9589
Create Date: 2025-02-23 14:07:57.139453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e546e920376'
down_revision = '350c62da9589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index('idx_branch_name', ['name'], unique=False)

    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('request_datetime', sa.DateTime(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('in-progress', 'closed', 'transferred', name='request_status'), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index('idx_client_name', ['client_name'], unique=False)
        batch_op.create_index('idx_phone_number', ['phone_number'], unique=False)

    op.create_table('request_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('updated_fields', sa.JSON(), nullable=False),
    sa.Column('previous_values', sa.JSON(), nullable=False),
    sa.Column('new_values', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('old_branch_id', sa.Integer(), nullable=False),
    sa.Column('new_branch_id', sa.Integer(), nullable=False),
    sa.Column('transferred_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['new_branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['old_branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_transfers')
    op.drop_table('request_history')
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index('idx_phone_number')
        batch_op.drop_index('idx_client_name')

    op.drop_table('requests')
    op.drop_table('managers')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index('idx_branch_name')

    op.drop_table('branches')
    # ### end Alembic commands ###
