"""empty message

Revision ID: d3167a050b2a
Revises: 2414e5a01389
Create Date: 2025-03-07 15:04:56.228494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3167a050b2a'
down_revision = '2414e5a01389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index('idx_branch_name', ['name'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['branch_name'], ['branches.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('idx_is_deleted', ['is_deleted'], unique=False)
        batch_op.create_index('idx_phone_number', ['phone_number'], unique=False)

    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['branch_name'], ['branches.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.create_index('idx_manager_name', ['name'], unique=False)

    op.create_table('application_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('updated_fields', sa.JSON(), nullable=False),
    sa.Column('previous_values', sa.JSON(), nullable=False),
    sa.Column('new_values', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_history')
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.drop_index('idx_manager_name')

    op.drop_table('managers')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('idx_phone_number')
        batch_op.drop_index('idx_is_deleted')

    op.drop_table('applications')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index('idx_branch_name')

    op.drop_table('branches')
    op.drop_table('admin')
    # ### end Alembic commands ###
