"""empty message

Revision ID: f0fbbdd45fa1
Revises: d3167a050b2a
Create Date: 2025-03-07 15:38:12.103180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0fbbdd45fa1'
down_revision = 'd3167a050b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
