"""empty message

Revision ID: fade1d82dd2c
Revises: fc026bfcb887
Create Date: 2025-02-21 23:11:33.736675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fade1d82dd2c'
down_revision = 'fc026bfcb887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index('idx_branch_name')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index('idx_client_name')
        batch_op.drop_index('idx_phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index('idx_phone_number', ['phone_number'], unique=False)
        batch_op.create_index('idx_client_name', ['client_name'], unique=False)
        batch_op.alter_column('notes',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index('idx_branch_name', ['name'], unique=False)

    # ### end Alembic commands ###
